language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
cache:
  directories:
    - .tmp/
    - ivy/
    - $HOME/.ivy2/

env:
  global:
    - _ANT_VERSION=1.9.13
    - _CLOC_VERSION=1.80
    - _PMD_VERSION=6.6.0
    - _IVY_VERSION=2.5.0-rc1
    - PACKAGE_VERSION=0.3.$TRAVIS_BUILD_NUMBER

install:
  - if [ ! -d .tmp ]; then mkdir .tmp; fi
  # SFDX CLI
  - cd .tmp && npm install sfdx-cli --loglevel info --cache npm-cache && cd ..
  - export SFDX_HOME=$TRAVIS_BUILD_DIR/.tmp/node_modules/.bin
  - export PATH=$SFDX_HOME:$PATH
  # Apache Ant
  - if [ ! -f .tmp/apache-ant-$_ANT_VERSION/bin/ant ]; then wget -nv -O .tmp/apache-ant-$_ANT_VERSION-bin.tar.gz http://mirrors.ircam.fr/pub/apache//ant/binaries/apache-ant-$_ANT_VERSION-bin.tar.gz && tar -xzvf .tmp/apache-ant-$_ANT_VERSION-bin.tar.gz -C .tmp; fi
  - export ANT_HOME=$TRAVIS_BUILD_DIR/.tmp/apache-ant-$_ANT_VERSION
  # PMD
  - if [ ! -f .tmp/pmd-bin-$_PMD_VERSION/bin/run.sh ]; then wget -nv -O .tmp/pmd-bin-$_PMD_VERSION.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F$_PMD_VERSION/pmd-bin-$_PMD_VERSION.zip && unzip .tmp/pmd-bin-$_PMD_VERSION.zip -d .tmp; fi
  - export PMD_HOME=$TRAVIS_BUILD_DIR/.tmp/pmd-bin-$_PMD_VERSION
  # CLOC
  - if [ ! -f .tmp/cloc.pl ]; then wget -nv -O .tmp/cloc.pl https://github.com/AlDanial/cloc/releases/download/$_CLOC_VERSION/cloc-$_CLOC_VERSION.pl; fi
  # Apache Ivy
  - if [ ! -d ivy ]; then mkdir ivy; fi
  - if [ ! -f ivy/ivy.jar ]; then wget -nv -O ivy/ivy.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/$_IVY_VERSION/ivy-$_IVY_VERSION.jar; fi
  - $JAVA_HOME/bin/java -jar ivy/ivy.jar -retrieve "ivy/lib/[conf]/[artifact].[ext]"

script:
  - $ANT_HOME/bin/ant -noclasspath -nouserlib -noinput -lib "ivy/lib/test" -lib "$PMD_HOME/lib" -logger org.apache.tools.ant.listener.AnsiColorLogger -f build.xml release

deploy:
  provider: releases
  api_key:
    secure: wShPQnxchn5rc99eRCrGZ034/nhTixhTKNyz+QnP0v+FSlnA0bj/QhOtnaBkLDcagyE2662FKoLDPkghq4TWBjKpkFyTgaplCA3kFH473b8uNPCCa1WpJnDTpy5atkxK/E2V27E+TYGJSKz43+lw/7wNHnEmH+6boqudztwcvRHf5ibD5NRrZLuuz1hXCWNw97C2xMayTjawLRyV5/EgTF4TzetxLeulygn0K1gt8tCKx2jgC6i1qxuD8Ed7/y0ka4dDck5uC+XQfYr/rrsldE4eVhKorw9Z6pZz/UjQjFaF5g2NtwjhME5Pp7Drofetx+Mr5vrTJWSvpHSTOldijAymNGIlRORFYNKNfiuyD4RdeymtU7nvxkfMtxV6w0b9Q3D5L48ajUXRdCcF/TG/MyVjYgVf3oV2UMqi4E+NoWxCU3Vq/r0anNW0AijOtaoU6ygJcu8zthDypXJq/RbrmEqJsy/Sfr+VFCN0LJdTOkm8WBB5ni7ukfpA0lKiSeyNdokSjh/tFuHc/STdjWyyS4CUZ7b4Cefy3eq1pNXTJTvwVSrmM0UHoSC1qITJMegGNE2zY10F29hSXWnlC2g4gwZFQ2YZDQcfeM8ZjWsU+WxQ7GawfQzrAIhVJjauFX7cTCJoJYoytkAe69GwqcIpDk9uDyexRq6kqS6aFNI+Q5Q=
  file_glob: true
  file: tmp/out/bin/*
  skip_cleanup: true
  on:
    tags: true
