language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
cache:
  directories:
    - .tmp/
    - ivy/
    - $HOME/.ivy2/

env:
  global:
    - _ANT_VERSION=1.9.12
    - _PMD_VERSION=6.5.0
    - _IVY_VERSION=2.5.0-rc1
    - PACKAGE_VERSION=0.2.$TRAVIS_BUILD_NUMBER

install:
  - if [ ! -d .tmp ]; then mkdir .tmp; fi
  # SFDX CLI
  - if [ ! -f .tmp/node_modules/.bin/sfdx ]; then cd .tmp && npm install sfdx-cli && cd ..; fi
  - export PATH=$TRAVIS_BUILD_DIR/.tmp/node_modules/.bin:$PATH
  # Apache Ant
  - if [ ! -f .tmp/apache-ant-$_ANT_VERSION-bin.tar.gz ]; then wget -nv -O .tmp/apache-ant-$_ANT_VERSION-bin.tar.gz http://apache.mirrors.ovh.net/ftp.apache.org/dist//ant/binaries/apache-ant-$_ANT_VERSION-bin.tar.gz && tar -xzvf .tmp/apache-ant-$_ANT_VERSION-bin.tar.gz -C .tmp; fi
  - export ANT_HOME=$TRAVIS_BUILD_DIR/.tmp/apache-ant-$_ANT_VERSION
  # PMD
  - if [ ! -f .tmp/pmd-bin-$_PMD_VERSION.zip ]; then wget -nv -O .tmp/pmd-bin-$_PMD_VERSION.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F$_PMD_VERSION/pmd-bin-$_PMD_VERSION.zip && unzip .tmp/pmd-bin-$_PMD_VERSION.zip -d .tmp; fi
  - export PMD_HOME=$TRAVIS_BUILD_DIR/.tmp/pmd-bin-$_PMD_VERSION
  # Apache Ivy
  - if [ ! -d ivy ]; then mkdir ivy; fi
  - if [ ! -f ivy/ivy.jar ]; then wget -nv -O ivy/ivy.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/$_IVY_VERSION/ivy-$_IVY_VERSION.jar; fi
  - $JAVA_HOME/bin/java -jar ivy/ivy.jar -retrieve "ivy/lib/[conf]/[artifact].[ext]"

script:
  - $ANT_HOME/bin/ant -noclasspath -nouserlib -noinput -lib "ivy/lib/test" -lib "$PMD_HOME/lib" -logger org.apache.tools.ant.listener.AnsiColorLogger -f build.xml release

deploy:
  provider: releases
  api_key:
    secure: "INNpFmoYvlXS14SoTTs2vbQNEz9dTui2oUxIEZoWFGtmK40VUBBvlkZZAoupWcflEvh0bacz7v2fjdmYexV9QKuRqIR9DOjdT0uYbELv37gAneH6utwqPJsdgIsyD0ZJs3SFDeN3pWnCSSDJH9+N/kPioXrFNLT3yltomIDG9SJbBSdx8nFs8tgRfRNORBZXUiE4cjTB5dd3J4j/3+Gahpxy6cTqlBfe3a5Bw31AhZvIKfNM0+IdF+WoJX5lMG3FF8ErFAZAQh/smrRxYdANBMvS2zZV/nik/WFVb/eYse+9SHk5Nz1OZtFdVoEsd0rVfCVTQqZGwZZikCevpRUmsJS8yTdXEov76NF/Zmpspt1QZdF+PHWe8Tiltk4xN04fNScL4I90mnge0dLKrHN1YpraoVd39U07jk17odz1dW1xfNOxbWH5uqPLGbKNjyzgyft4zX2j7+XSdPyemKoMfRzX718Wu4L5E7J8/31O+4siR0hNPITg+kY8YlvDlHtyDVvY0EBQR1KN1IOJG/yApw9cCpMzvxn/bJQFenYZxnFniHwPKgLnEtPtPUAFZTqgQDXJ/fvFWqNb0r9zmKE8rDVqtcvLFyerksd5PAH05WkutOXgu3dNWiY7U4l/hqd+P/4h5vIzOEAX2EoewV7lDZsHdIvnDtCd8cERSw5cd/g="
  file_glob: true
  file: tmp/out/bin/*
  skip_cleanup: true
  on:
    tags: true
